### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by beeb** [pinax-network/substreams-sink-discord#1]
I came across this sink looking at https://github.com/pinax-network/awesome-substreams

It seems to do exactly what I want, however I have trouble to run it and it fails with no error. I see looking at the dependencies that it uses deprecated substreams packages.

Is this software suppose to work in the current state of things? Or is there some maintenance work needed?

**Comment by DenisCarriere** [comment]
@beeb thanks for your interest, the repo is currently a bit outdated and would need to bump some dependencies and improve documentation 

@chamorin

**Comment by chamorin** [comment]
@beeb Some of the core dependencies of this project have seen big changes. I'll update the project 👍 Thanks for your interest!

**Comment by beeb** [comment]
Thank you for the quick reply!

**Comment by chamorin** [comment]
@beeb The `main` branch has been updated and should be working. Let me know if you're having issues 👍
